import { FILTER_TYPE, TYPE, TEXT_FORMATS } from '../../constants/filterConstants';

export const FILTER_CONFIG = [
  {
    fieldName: 'age',
    label: 'Age',
    filterType: FILTER_TYPE.dropdown,
    options: {
      A: 'below 18',
      B: 'between 18-25',
      C: 'between 25-50',
      D: 'above 50',
    },
    value: '',
    placeholder: 'Choose data source',
    isDisabled: false,
  },
  {
    fieldName: 'id',
    label: 'ID',
    filterType: FILTER_TYPE.inputField,
    type: TYPE.number,
    operator: '$eq',
    value: '',
    placeholder: 'Enter description',
    isDisabled: false,
  },
  {
    fieldName: 'scheduled_date',
    label: 'Scheduled Date',
    filterType: FILTER_TYPE.datePicker,
    placeholder: 'Choose a date',
    value: '',
    isDisabled: false,
  },
  {
    fieldName: 'full_name',
    label: 'Full Name',
    filterType: FILTER_TYPE.inputField,
    type: TYPE.text,
    operator: '$eq',
    format: TEXT_FORMATS.uppercase,
    value: '',
    placeholder: 'Enter description',
    isDisabled: false,
  },
  {
    fieldName: 'range',
    label: 'Range',
    type: 'number',
    filterType: FILTER_TYPE.range,
    value: {
      min: 1000,
      max: 3000,
    },
    min: 1000,
    max: 3000,
    isDisabled: false,
  },
];
